### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by ccwasden** [mariusciocan/parse-cloud-debugger#8]
Any clue what is causing the node.js server to die whenever I open localhost:5555?

```
undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/~~PATH_TO~~/parse-cloud-debugger-master/parse-cloud-debugger/src/index.js:143:25)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by khanxc** [comment]
@mariusciocan I have the same issue and your suggestion didn't help. Any ideas?

**Comment by mariusciocan** [comment]
@khanxc can you try with the latest version? Please send the error log if you still have this issue.

**Comment by khanxc** [comment]
Hi sorry for delayed response. This is my error log
```
Local Parse Cloud running at port 5555...
undefined:0


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/khan/Desktop/currently working/myapp/node_modules/parse-cloud-debugger/src/index.js:180:25)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by khanxc** [comment]
same with your demo cloned from github , any suggestions? This happens when i open localhost:5555 in safari

```
node startLocalDebugging.js 
Test job call success! 
Local Parse Cloud running at port 5555...
undefined:0


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/myname/Desktop/Cloned/parse-cloud-debugger/parse-cloud-debugger/src/index.js:180:25)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by amodaresi** [comment]
@mariusciocan 
How should I test the REST part?
When I test the curl command on localhost:5555 in terminal nothing happens and it seems that the requests that I enter just timeout.
Does it needs any changes for the REST api?

And another thing, does this debugger support saving objects and creating queries? And if does, Is there anyway to see the tables in my local system?

**Comment by balasivagnanam** [comment]
same error... TESTJOB failed as well..

```
C:\myapps\parseapp\rsvp>node startLocalDebugging.js
Unable to run function 'testJOB'. Function is not defined !
Local Parse Cloud running at port 5555...
undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (C:\myapps\parseapp\rsvp\node_modules\parse-c
loud-debugger\src\index.js:180:25)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by mariusciocan** [comment]
1. Make sure you have the latest version. git pull
2. I've tested using node 4.2.4 and everything was ok
3. Open in your browser http://localhost:3000 to see the example
4. Use http://localhost:5555 to make the Parse calls,but be aware that all the request from web example are made using Parse.run function.
5. If the 'testJOB' fails, please remove it from 'startLocalDebugging.js' file, line 20 or make sure you have it defined in 'cloud\main.js. file.
